name: 
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  - python-dotenv
  - numpy
  - pandas
  - jupyterlab
  - ipywidgets
  - matplotlib
  - jupyter-dash
  - requests
  - multitasking
  - pip:
    - pathlib
    - yfinance
    - alpha_vantage
    - quandl 
